#!/usr/bin/env python3
"""Static server for the OrcaRouter UI evidence harness.

Serves the production build of the evidence app and the catalog JSON produced by
the shipped capability filters. Using a built bundle (rather than a dev server)
keeps React Fast Refresh from remounting the component mid-interaction.
"""

import json
import mimetypes
import sys
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import urlparse, parse_qs

# Generated by run_evidence.py; kept outside the repository working tree.
ROOT = Path("/tmp/orca-evidence/dist")
DATA = Path("/tmp/orca-evidence/data")


class Handler(BaseHTTPRequestHandler):
    def log_message(self, *args):  # keep the evidence log quiet
        pass

    def _json(self, payload):
        body = json.dumps(payload).encode()
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def do_GET(self):
        parsed = urlparse(self.path)
        query = parse_qs(parsed.query)

        if parsed.path in ("/orca-evidence/catalog", "/orca-evidence/seed"):
            modalities = (query.get("inputModalities", ["text"])[0] or "text").split(",")
            modalities = [m for m in modalities if m]
            catalog = json.loads((DATA / "catalog.json").read_text())
            live = parsed.path.endswith("catalog")

            if not live:
                models = catalog["seed"]
            elif "image" in modalities:
                models = catalog["multimodal"]
            else:
                models = catalog["text"]

            self._json({
                "ok": True,
                "models": models,
                "source": "live" if live else "seed",
                "degraded": not live,
                "total": catalog["total"],
            })
            return

        rel = parsed.path.lstrip("/") or "index.html"
        target = (ROOT / rel).resolve()
        if not str(target).startswith(str(ROOT)) or not target.is_file():
            target = ROOT / "index.html"
        body = target.read_bytes()
        ctype = mimetypes.guess_type(str(target))[0] or "application/octet-stream"
        self.send_response(200)
        self.send_header("Content-Type", ctype)
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)


if __name__ == "__main__":
    port = int(sys.argv[1]) if len(sys.argv) > 1 else 5199
    ThreadingHTTPServer(("127.0.0.1", port), Handler).serve_forever()
